### PR TITLE
UI improvement

### PR DESCRIPTION
**Pull request by 408796571**
Overall, focus on mobile responsive layout with following additional changes:
1. set default minimum div height under "Dashboard"
2. center "You have no activity!"
3. re-organize "Send" layout to accommodate for more real estate 
4. center settings actions toggle/button layout position
5. disable default window menu to give it more unified app look

### CODE REVIEW

**Review by JSKitty — COMMENTED** [review]
Looking great! The mobile / reactivity enhancements are warmly welcome, settings centering improvements are nice.

The only thing I see which looks a bit 'off' is the 'Send' page changes, this UI doesn't look too right in a list format, it introduces a bit too much verticalilty for a Desktop app, although on mobile this format makes sense as it can fit more space on mobile.

Perhaps we could media query this, using the old format on desktops, and this 'list format' on smaller / vertical / portrait displays?

**Comment by 408796571** [comment]
@JSKitty haha, somehow your reply reflects exactly my thought about the 'Send' page without the recommendation part :) 
I'll get on that and use verticality for mobile/tablet and keep the original format for the desktop! Thanks for the recommendation. 

I think we can learn a lot from Exodus desktop wallet from both UI/UX and features.

**Comment by JSKitty** [comment]
Sweet! Agreed on the Exodus part, once SCP tokens have a value associated to them (exchange rate on SC Exchange) then it's one of my goals to build a really sleek portfolio display, pie chart, etc, similar to what Exodus have, and a similar elegant UI / UX, they're certainly a good inspiration. :D

**Comment by JSKitty** [comment]
Latest commits looking sweet at multiple resolutions! I think it's worth merging now, so happy to merge if you believe it's ready.
Will add some minor tweaks afterwards. 🚀

**Comment by 408796571** [comment]
Nice! I believe it's ready. I don't want to keep packing stuff into one PR, then it becomes never ending loop.. 😄

**Comment by JSKitty** [comment]
Merged, credits will be given within the next Release Notes! 😄 🚀

**Pull request merged**
